In [1]:
import pandas as pd
import numpy as np

In [2]:
# Load dataset :-

data = pd.read_csv("train.csv")

In [3]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680

In [4]:
data.columns.tolist()

['Row ID',
 'Order ID',
 'Order Date',
 'Ship Date',
 'Ship Mode',
 'Customer ID',
 'Customer Name',
 'Segment',
 'Country',
 'City',
 'State',
 'Postal Code',
 'Region',
 'Product ID',
 'Category',
 'Sub-Category',
 'Product Name',
 'Sales']

In [5]:
data.shape

(9800, 18)

In [6]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     9800 non-null   str
 3   Ship Date      9800 non-null   str
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9789 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: float64(2), int64(1), str(15)
memory usage: 3.1 MB

In [7]:
data.duplicated().sum()

np.int64(0)

In [ ]:
data = data.drop_duplicates()

In [10]:
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [11]:
data["Postal Code"] = data["Postal Code"].fillna(data["Postal Code"].median())

In [15]:
data["Postal Code"].isna().sum()

np.int64(0)

In [16]:
data.isna().sum().sum()

np.int64(0)

In [17]:
(data.isnull().sum() / len(data) * 100).sort_values(ascending=False)

Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
dtype: float64

In [18]:
data["Order Date"] = pd.to_datetime(data["Order Date"], errors="coerce")

In [19]:
data["Ship Date"] = pd.to_datetime(data["Ship Date"],errors="coerce")

In [20]:
data[["Order Date", "Ship Date"]].dtypes

Order Date    datetime64[us]
Ship Date     datetime64[us]
dtype: object

In [22]:
data["Postal Code"] = pd.to_numeric(data["Postal Code"], errors="coerce")

In [23]:
data["Postal Code"].dtypes

dtype('float64')

In [25]:
numeric_columns= [
    "Sales",
    "Postal Code"
]

In [28]:
for col in numeric_columns:
    data[col] = pd.to_numeric(
        data[col],
        errors="coerce"
    )

In [30]:
data[numeric_columns].dtypes

Sales          float64
Postal Code    float64
dtype: object

In [32]:
data[numeric_columns].isnull().sum()

Sales          0
Postal Code    0
dtype: int64

In [33]:
for col in ["Sales"]:
    data[col] = data[col].fillna(
        data[col].median()
    )

In [34]:
text_columns = data.select_dtypes(
    include="object"
).columns

text_columns

C:\Users\rajak\AppData\Local\Temp\ipykernel_15372\2839548384.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = data.select_dtypes(

Index(['Order ID', 'Ship Mode', 'Customer ID', 'Customer Name', 'Segment',
       'Country', 'City', 'State', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name'],
      dtype='str')

In [35]:
for col in text_columns:
    data[col] = data[col].str.strip()

In [37]:
data[text_columns].isnull().sum()

Order ID         0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
dtype: int64

In [38]:
for col in text_columns:
    data[col] = data[col].fillna("Unknown")

In [39]:
(data["Sales"] < 0).sum()

np.int64(0)

In [40]:
print("Invalid Order Dates:",
      data["Order Date"].isnull().sum())

print("Invalid Ship Dates:",
      data["Ship Date"].isnull().sum())

Invalid Order Dates: 5841
Invalid Ship Dates: 5985

In [41]:
(data["Ship Date"] < data["Order Date"]).sum()

np.int64(0)

In [42]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 9800 entries, 0 to 9799
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9800 non-null   int64
 1   Order ID       9800 non-null   str
 2   Order Date     3959 non-null   datetime64[us]
 3   Ship Date      3815 non-null   datetime64[us]
 4   Ship Mode      9800 non-null   str
 5   Customer ID    9800 non-null   str
 6   Customer Name  9800 non-null   str
 7   Segment        9800 non-null   str
 8   Country        9800 non-null   str
 9   City           9800 non-null   str
 10  State          9800 non-null   str
 11  Postal Code    9800 non-null   float64
 12  Region         9800 non-null   str
 13  Product ID     9800 non-null   str
 14  Category       9800 non-null   str
 15  Sub-Category   9800 non-null   str
 16  Product Name   9800 non-null   str
 17  Sales          9800 non-null   float64
dtypes: datetime64[us](2), float64(2), int64(1), str(13)
memory usage: 2.9 MB

In [43]:
data.describe()

,Row ID,Order Date,Ship Date,Postal Code,Sales
count,9800.000000,3959,3815,9800.000000,9800.000000
mean,4900.500000,2017-03-14 18:19:11.199798,2017-04-09 17:04:02.516382,55276.498571,230.769059
min,1.000000,2015-01-02 00:00:00,2015-01-04 00:00:00,1040.000000,0.444000
25%,2450.750000,2016-04-05 00:00:00,2016-04-12 00:00:00,23223.000000,17.248000
50%,4900.500000,2017-05-02 00:00:00,2017-06-06 00:00:00,58103.000000,54.490000
75%,7350.250000,2018-03-07 00:00:00,2018-05-01 00:00:00,90008.000000,210.605000
max,9800.000000,2018-12-11 00:00:00,2019-05-01 00:00:00,99301.000000,22638.480000
std,2829.160653,NaN,NaN,32023.374393,626.651875

In [44]:
data.to_csv("cleaned_sales.csv",index=False)